/*! Copyright (C) 2009 Apertus, All Rights Reserved
 *! Author : Apertus Team
-----------------------------------------------------------------------------**
 *!
 *!  This program is free software: you can redistribute it and/or modify
 *!  it under the terms of the GNU General Public License as published by
 *!  the Free Software Foundation, either version 3 of the License, or
 *!  (at your option) any later version.
 *!
 *!  This program is distributed in the hope that it will be useful,
 *!  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *!  GNU General Public License for more details.
 *!
 *!  You should have received a copy of the GNU General Public License
 *!  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *!
-----------------------------------------------------------------------------**/

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JTextField;
import javax.swing.text.Caret;

public class NumericalInputPanelIP extends javax.swing.JPanel {

    JTextField FieldParent;
    String TargetCard;
    ElphelVision Parent;
    int FocusOwnerIndex = 0;

    public NumericalInputPanelIP(ElphelVision parent) {
        this.Parent = parent;

        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void Load(String Varname, String value, JTextField parent, String targetCard) {
        this.FieldParent = parent;
        this.VarName.setText(Varname);
        this.TargetCard = targetCard;

        String[] IPvalue = new String[4];

        IPvalue = value.split("\\.");
        this.NumberField1.setText(String.valueOf(IPvalue[0]));
        this.NumberField2.setText(String.valueOf(IPvalue[1]));
        this.NumberField3.setText(String.valueOf(IPvalue[2]));
        this.NumberField4.setText(String.valueOf(IPvalue[3]));

        NumberField1.requestFocus();
        NumberField1.setCaretPosition(0);
        NumberField1.getCaret().setVisible(true);
        FocusOwnerIndex = 1;
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Keypad = new javax.swing.JPanel();
        Number1 = new EButton(Parent);
        Number2 = new EButton(Parent);
        Number3 = new EButton(Parent);
        Number4 = new EButton(Parent);
        Number5 = new EButton(Parent);
        Number6 = new EButton(Parent);
        Number7 = new EButton(Parent);
        Number8 = new EButton(Parent);
        Number9 = new EButton(Parent);
        NumberClear = new EButton(Parent);
        Number0 = new EButton(Parent);
        NumberPlusOne = new EButton(Parent);
        NumberPlusTen = new EButton(Parent);
        NumberMinusOne = new EButton(Parent);
        NumberMinus10 = new EButton(Parent);
        BackspaceButton = new EButton(Parent);
        DelButton = new EButton(Parent);
        NumberClear1 = new EButton(Parent);
        NumberPanel = new javax.swing.JPanel();
        VarName = new javax.swing.JLabel();
        NumberField1 = new javax.swing.JTextField();
        RightButton = new EButton(Parent);
        LeftButton = new EButton(Parent);
        NumberField3 = new javax.swing.JTextField();
        NumberField2 = new javax.swing.JTextField();
        NumberField4 = new javax.swing.JTextField();
        VarName1 = new javax.swing.JLabel();
        VarName2 = new javax.swing.JLabel();
        VarName3 = new javax.swing.JLabel();
        Validation = new javax.swing.JLabel();
        ConfirmationPanel = new javax.swing.JPanel();
        SettingsCancelButton = new EButton(Parent);
        SettingsOKButton = new EButton(Parent);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setPreferredSize(new java.awt.Dimension(1024, 600));

        Keypad.setBackground(new java.awt.Color(0, 0, 0));

        Number1.setText("1");
        Number1.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number1.setPreferredSize(new java.awt.Dimension(100, 60));
        Number1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Number1MouseClicked(evt);
            }
        });

        Number2.setText("2");
        Number2.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number2.setPreferredSize(new java.awt.Dimension(100, 60));
        Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number2ActionPerformed(evt);
            }
        });

        Number3.setText("3");
        Number3.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number3.setPreferredSize(new java.awt.Dimension(100, 60));
        Number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number3ActionPerformed(evt);
            }
        });

        Number4.setText("4");
        Number4.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number4.setPreferredSize(new java.awt.Dimension(100, 60));
        Number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number4ActionPerformed(evt);
            }
        });

        Number5.setText("5");
        Number5.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number5.setPreferredSize(new java.awt.Dimension(100, 60));
        Number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number5ActionPerformed(evt);
            }
        });

        Number6.setText("6");
        Number6.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number6.setPreferredSize(new java.awt.Dimension(100, 60));
        Number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number6ActionPerformed(evt);
            }
        });

        Number7.setText("7");
        Number7.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number7.setPreferredSize(new java.awt.Dimension(100, 60));
        Number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number7ActionPerformed(evt);
            }
        });

        Number8.setText("8");
        Number8.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number8.setPreferredSize(new java.awt.Dimension(100, 60));
        Number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number8ActionPerformed(evt);
            }
        });

        Number9.setText("9");
        Number9.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number9.setPreferredSize(new java.awt.Dimension(100, 60));
        Number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number9ActionPerformed(evt);
            }
        });

        NumberClear.setText("Clear All");
        NumberClear.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberClear.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberClearActionPerformed(evt);
            }
        });

        Number0.setText("0");
        Number0.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number0.setPreferredSize(new java.awt.Dimension(100, 60));
        Number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number0ActionPerformed(evt);
            }
        });

        NumberPlusOne.setText("+1");
        NumberPlusOne.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberPlusOne.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberPlusOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberPlusOneActionPerformed(evt);
            }
        });

        NumberPlusTen.setText("+10");
        NumberPlusTen.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberPlusTen.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberPlusTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberPlusTenActionPerformed(evt);
            }
        });

        NumberMinusOne.setText("-1");
        NumberMinusOne.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberMinusOne.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberMinusOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberMinusOneActionPerformed(evt);
            }
        });

        NumberMinus10.setText("-10");
        NumberMinus10.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberMinus10.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberMinus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberMinus10ActionPerformed(evt);
            }
        });

        BackspaceButton.setText("Backspace");
        BackspaceButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        BackspaceButton.setPreferredSize(new java.awt.Dimension(100, 60));
        BackspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceButtonActionPerformed(evt);
            }
        });

        DelButton.setText("Del");
        DelButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        DelButton.setPreferredSize(new java.awt.Dimension(100, 60));
        DelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelButtonActionPerformed(evt);
            }
        });

        NumberClear1.setText("Clear");
        NumberClear1.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberClear1.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeypadLayout = new javax.swing.GroupLayout(Keypad);
        Keypad.setLayout(KeypadLayout);
        KeypadLayout.setHorizontalGroup(
            KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadLayout.createSequentialGroup()
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KeypadLayout.createSequentialGroup()
                            .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(KeypadLayout.createSequentialGroup()
                            .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KeypadLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Number7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(KeypadLayout.createSequentialGroup()
                                .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NumberClear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumberMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumberPlusOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberPlusTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberMinusOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumberClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackspaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addContainerGap())
        );
        KeypadLayout.setVerticalGroup(
            KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addComponent(BackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberPlusTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberPlusOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberMinusOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberClear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NumberPanel.setBackground(java.awt.Color.black);

        VarName.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        VarName.setForeground(new java.awt.Color(255, 255, 255));
        VarName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VarName.setText("Name");
        VarName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VarName.setAlignmentY(0.0F);
        VarName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        VarName.setIconTextGap(0);
        VarName.setInheritsPopupMenu(false);
        VarName.setRequestFocusEnabled(false);
        VarName.setVerifyInputWhenFocusTarget(false);
        VarName.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        NumberField1.setBackground(new java.awt.Color(0, 0, 0));
        NumberField1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18));
        NumberField1.setForeground(new java.awt.Color(255, 255, 255));
        NumberField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumberField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 148, 148)));
        NumberField1.setCaretColor(new java.awt.Color(255, 255, 255));
        NumberField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NumberField1CaretUpdate(evt);
            }
        });
        NumberField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumberField1FocusGained(evt);
            }
        });

        RightButton.setText("->");
        RightButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        RightButton.setPreferredSize(new java.awt.Dimension(100, 60));
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });

        LeftButton.setText("<-");
        LeftButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        LeftButton.setPreferredSize(new java.awt.Dimension(100, 60));
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        NumberField3.setBackground(new java.awt.Color(0, 0, 0));
        NumberField3.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18));
        NumberField3.setForeground(new java.awt.Color(255, 255, 255));
        NumberField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumberField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 148, 148)));
        NumberField3.setCaretColor(new java.awt.Color(255, 255, 255));
        NumberField3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NumberField3CaretUpdate(evt);
            }
        });
        NumberField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumberField3FocusGained(evt);
            }
        });

        NumberField2.setBackground(new java.awt.Color(0, 0, 0));
        NumberField2.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18));
        NumberField2.setForeground(new java.awt.Color(255, 255, 255));
        NumberField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumberField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 148, 148)));
        NumberField2.setCaretColor(new java.awt.Color(255, 255, 255));
        NumberField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NumberField2CaretUpdate(evt);
            }
        });
        NumberField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumberField2FocusGained(evt);
            }
        });

        NumberField4.setBackground(new java.awt.Color(0, 0, 0));
        NumberField4.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18));
        NumberField4.setForeground(new java.awt.Color(255, 255, 255));
        NumberField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumberField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 148, 148)));
        NumberField4.setCaretColor(new java.awt.Color(255, 255, 255));
        NumberField4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NumberField4CaretUpdate(evt);
            }
        });
        NumberField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumberField4FocusGained(evt);
            }
        });

        VarName1.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        VarName1.setForeground(new java.awt.Color(255, 255, 255));
        VarName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VarName1.setText(".");
        VarName1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VarName1.setAlignmentY(0.0F);
        VarName1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        VarName1.setIconTextGap(0);
        VarName1.setInheritsPopupMenu(false);
        VarName1.setRequestFocusEnabled(false);
        VarName1.setVerifyInputWhenFocusTarget(false);
        VarName1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        VarName2.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        VarName2.setForeground(new java.awt.Color(255, 255, 255));
        VarName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VarName2.setText(".");
        VarName2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VarName2.setAlignmentY(0.0F);
        VarName2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        VarName2.setIconTextGap(0);
        VarName2.setInheritsPopupMenu(false);
        VarName2.setRequestFocusEnabled(false);
        VarName2.setVerifyInputWhenFocusTarget(false);
        VarName2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        VarName3.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        VarName3.setForeground(new java.awt.Color(255, 255, 255));
        VarName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VarName3.setText(".");
        VarName3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VarName3.setAlignmentY(0.0F);
        VarName3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        VarName3.setIconTextGap(0);
        VarName3.setInheritsPopupMenu(false);
        VarName3.setRequestFocusEnabled(false);
        VarName3.setVerifyInputWhenFocusTarget(false);
        VarName3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout NumberPanelLayout = new javax.swing.GroupLayout(NumberPanel);
        NumberPanel.setLayout(NumberPanelLayout);
        NumberPanelLayout.setHorizontalGroup(
            NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VarName)
                    .addGroup(NumberPanelLayout.createSequentialGroup()
                        .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NumberPanelLayout.createSequentialGroup()
                                .addComponent(NumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VarName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberField2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VarName2)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NumberPanelLayout.createSequentialGroup()
                                .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(NumberField3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VarName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumberField4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        NumberPanelLayout.setVerticalGroup(
            NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NumberField4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VarName3)
                    .addGroup(NumberPanelLayout.createSequentialGroup()
                        .addComponent(VarName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberField2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(VarName1)
                    .addComponent(VarName2))
                .addGap(18, 18, 18)
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Validation.setForeground(new java.awt.Color(180, 1, 1));

        ConfirmationPanel.setBackground(java.awt.Color.black);

        SettingsCancelButton.setText("Cancel");
        SettingsCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsCancelButtonActionPerformed(evt);
            }
        });

        SettingsOKButton.setText("OK");
        SettingsOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfirmationPanelLayout = new javax.swing.GroupLayout(ConfirmationPanel);
        ConfirmationPanel.setLayout(ConfirmationPanelLayout);
        ConfirmationPanelLayout.setHorizontalGroup(
            ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationPanelLayout.createSequentialGroup()
                .addComponent(SettingsOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SettingsCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ConfirmationPanelLayout.setVerticalGroup(
            ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SettingsOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(SettingsCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Validation, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(840, Short.MAX_VALUE)
                .addComponent(ConfirmationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Keypad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Validation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Keypad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(ConfirmationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsOKButtonActionPerformed
        this.FieldParent.setText(NumberField1.getText() + "." + NumberField2.getText() + "." + NumberField3.getText() + "." + NumberField4.getText());

        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), TargetCard);
    }//GEN-LAST:event_SettingsOKButtonActionPerformed

    private void SettingsCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsCancelButtonActionPerformed
        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), TargetCard);
    }//GEN-LAST:event_SettingsCancelButtonActionPerformed

    private void NumberField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NumberField1CaretUpdate
        Validate();
    }//GEN-LAST:event_NumberField1CaretUpdate

    void AppendCharacter(String character) {
        if (FocusOwnerIndex == 1) {
            int tmpcaretpos = NumberField1.getCaretPosition(); // save positon of the caret so we can use it again after replacing the string
            NumberField1.setText(NumberField1.getText().substring(0, NumberField1.getCaretPosition()) + character + NumberField1.getText().substring(NumberField1.getCaretPosition(), NumberField1.getText().length()));
            NumberField1.setCaretPosition(tmpcaretpos + 1); // use the save caret position again
            NumberField1.getCaret().setVisible(true);
        }
        if (FocusOwnerIndex == 2) {
            int tmpcaretpos = NumberField2.getCaretPosition(); // save positon of the caret so we can use it again after replacing the string
            NumberField2.setText(NumberField2.getText().substring(0, NumberField2.getCaretPosition()) + character + NumberField2.getText().substring(NumberField2.getCaretPosition(), NumberField2.getText().length()));
            NumberField2.setCaretPosition(tmpcaretpos + 1); // use the save caret position again
            NumberField2.getCaret().setVisible(true);
        }
        if (FocusOwnerIndex == 3) {
            int tmpcaretpos = NumberField3.getCaretPosition(); // save positon of the caret so we can use it again after replacing the string
            NumberField3.setText(NumberField3.getText().substring(0, NumberField3.getCaretPosition()) + character + NumberField3.getText().substring(NumberField3.getCaretPosition(), NumberField3.getText().length()));
            NumberField3.setCaretPosition(tmpcaretpos + 1); // use the save caret position again
            NumberField3.getCaret().setVisible(true);
        }
        if (FocusOwnerIndex == 4) {
            int tmpcaretpos = NumberField4.getCaretPosition(); // save positon of the caret so we can use it again after replacing the string
            NumberField4.setText(NumberField4.getText().substring(0, NumberField4.getCaretPosition()) + character + NumberField4.getText().substring(NumberField4.getCaretPosition(), NumberField4.getText().length()));
            NumberField4.setCaretPosition(tmpcaretpos + 1); // use the save caret position again
            NumberField4.getCaret().setVisible(true);
        }
        Validate();
    }

    private void Validate() {
        if (!"".equals(NumberField1.getText())) {
            if (Integer.parseInt(NumberField1.getText()) > 254) {
                NumberField1.setText("254");
            }
            if (Integer.parseInt(NumberField1.getText()) < 0) {
                NumberField1.setText("0");
            }
        }
        if (!"".equals(NumberField2.getText())) {
            if (Integer.parseInt(NumberField2.getText()) > 254) {
                NumberField2.setText("254");
            }
            if (Integer.parseInt(NumberField2.getText()) < 0) {
                NumberField2.setText("0");
            }
        }
        if (!"".equals(NumberField3.getText())) {
            if (Integer.parseInt(NumberField3.getText()) > 254) {
                NumberField3.setText("254");
            }
            if (Integer.parseInt(NumberField3.getText()) < 0) {
                NumberField3.setText("0");
            }
        }
        if (!"".equals(NumberField4.getText())) {
            if (Integer.parseInt(NumberField4.getText()) > 254) {
                NumberField4.setText("254");
            }
            if (Integer.parseInt(NumberField4.getText()) < 0) {
                NumberField4.setText("0");
            }
        }
    }

    private void Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number2ActionPerformed
        AppendCharacter("2");
    }//GEN-LAST:event_Number2ActionPerformed

    private void Number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number3ActionPerformed
        AppendCharacter("3");
    }//GEN-LAST:event_Number3ActionPerformed

    private void Number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number4ActionPerformed
        AppendCharacter("4");
    }//GEN-LAST:event_Number4ActionPerformed

    private void Number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number5ActionPerformed
        AppendCharacter("5");
    }//GEN-LAST:event_Number5ActionPerformed

    private void Number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number6ActionPerformed
        AppendCharacter("6");
    }//GEN-LAST:event_Number6ActionPerformed

    private void Number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number7ActionPerformed
        AppendCharacter("7");
    }//GEN-LAST:event_Number7ActionPerformed

    private void Number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number8ActionPerformed
        AppendCharacter("8");
    }//GEN-LAST:event_Number8ActionPerformed

    private void Number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number9ActionPerformed
        AppendCharacter("9");
    }//GEN-LAST:event_Number9ActionPerformed

    private void NumberClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberClearActionPerformed
        NumberField1.setText("");
        NumberField2.setText("");
        NumberField3.setText("");
        NumberField4.setText("");
    }//GEN-LAST:event_NumberClearActionPerformed

    private void Number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number0ActionPerformed
        AppendCharacter("0");
    }//GEN-LAST:event_Number0ActionPerformed

    private void DelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelButtonActionPerformed
        if (FocusOwnerIndex == 1) {
            if (NumberField1.getCaretPosition() != NumberField1.getText().length()) { // only do something if the caret is not the at the end
                int tmpcaretpos = NumberField1.getCaretPosition();
                NumberField1.setText(NumberField1.getText().substring(0, NumberField1.getCaretPosition()) + NumberField1.getText().substring(NumberField1.getCaretPosition() + 1, NumberField1.getText().length()));
                NumberField1.setCaretPosition(tmpcaretpos);
            }
        }
        if (FocusOwnerIndex == 2) {
            if (NumberField2.getCaretPosition() != NumberField2.getText().length()) { // only do something if the caret is not the at the end
                int tmpcaretpos = NumberField2.getCaretPosition();
                NumberField2.setText(NumberField2.getText().substring(0, NumberField2.getCaretPosition()) + NumberField2.getText().substring(NumberField2.getCaretPosition() + 1, NumberField2.getText().length()));
                NumberField2.setCaretPosition(tmpcaretpos);
            }
        }
        if (FocusOwnerIndex == 3) {
            if (NumberField3.getCaretPosition() != NumberField3.getText().length()) { // only do something if the caret is not the at the end
                int tmpcaretpos = NumberField3.getCaretPosition();
                NumberField3.setText(NumberField3.getText().substring(0, NumberField3.getCaretPosition()) + NumberField3.getText().substring(NumberField3.getCaretPosition() + 1, NumberField3.getText().length()));
                NumberField3.setCaretPosition(tmpcaretpos);
            }
        }
        if (FocusOwnerIndex == 4) {
            if (NumberField4.getCaretPosition() != NumberField4.getText().length()) { // only do something if the caret is not the at the end
                int tmpcaretpos = NumberField4.getCaretPosition();
                NumberField4.setText(NumberField4.getText().substring(0, NumberField4.getCaretPosition()) + NumberField4.getText().substring(NumberField4.getCaretPosition() + 1, NumberField4.getText().length()));
                NumberField4.setCaretPosition(tmpcaretpos);
            }
        }
        Validate();
    }//GEN-LAST:event_DelButtonActionPerformed

    private void BackspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceButtonActionPerformed
        if (FocusOwnerIndex == 1) {
            if (NumberField1.getCaretPosition() != 0) { // only do something if the caret is not the at the beginning
                int tmpcaretpos = NumberField1.getCaretPosition();
                NumberField1.setText(NumberField1.getText().substring(0, NumberField1.getCaretPosition() - 1) + NumberField1.getText().substring(NumberField1.getCaretPosition(), NumberField1.getText().length()));
                NumberField1.setCaretPosition(tmpcaretpos - 1);
            }
        }
        if (FocusOwnerIndex == 2) {
            if (NumberField2.getCaretPosition() != 0) { // only do something if the caret is not the at the beginning
                int tmpcaretpos = NumberField2.getCaretPosition();
                NumberField2.setText(NumberField2.getText().substring(0, NumberField2.getCaretPosition() - 1) + NumberField2.getText().substring(NumberField2.getCaretPosition(), NumberField2.getText().length()));
                NumberField2.setCaretPosition(tmpcaretpos - 1);
            }
        }
        if (FocusOwnerIndex == 3) {
            if (NumberField3.getCaretPosition() != 0) { // only do something if the caret is not the at the beginning
                int tmpcaretpos = NumberField3.getCaretPosition();
                NumberField3.setText(NumberField3.getText().substring(0, NumberField3.getCaretPosition() - 1) + NumberField3.getText().substring(NumberField3.getCaretPosition(), NumberField3.getText().length()));
                NumberField3.setCaretPosition(tmpcaretpos - 1);
            }
        }
        if (FocusOwnerIndex == 4) {
            if (NumberField4.getCaretPosition() != 0) { // only do something if the caret is not the at the beginning
                int tmpcaretpos = NumberField4.getCaretPosition();
                NumberField4.setText(NumberField4.getText().substring(0, NumberField4.getCaretPosition() - 1) + NumberField4.getText().substring(NumberField4.getCaretPosition(), NumberField4.getText().length()));
                NumberField4.setCaretPosition(tmpcaretpos - 1);
            }
        }
        Validate();
    }//GEN-LAST:event_BackspaceButtonActionPerformed

    private void NumberPlusOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberPlusOneActionPerformed
        if (FocusOwnerIndex == 1) {
            int temp = Integer.parseInt(NumberField1.getText()) + 1;
            NumberField1.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 2) {
            int temp = Integer.parseInt(NumberField2.getText()) + 1;
            NumberField2.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 3) {
            int temp = Integer.parseInt(NumberField3.getText()) + 1;
            NumberField3.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 4) {
            int temp = Integer.parseInt(NumberField4.getText()) + 1;
            NumberField4.setText(String.valueOf(temp));
        }
        Validate();
    }//GEN-LAST:event_NumberPlusOneActionPerformed

    private void NumberPlusTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberPlusTenActionPerformed
        if (FocusOwnerIndex == 1) {
            int temp = Integer.parseInt(NumberField1.getText()) + 10;
            NumberField1.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 2) {
            int temp = Integer.parseInt(NumberField2.getText()) + 10;
            NumberField2.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 3) {
            int temp = Integer.parseInt(NumberField3.getText()) + 10;
            NumberField3.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 4) {
            int temp = Integer.parseInt(NumberField4.getText()) + 10;
            NumberField4.setText(String.valueOf(temp));
        }
        Validate();
    }//GEN-LAST:event_NumberPlusTenActionPerformed

    private void NumberMinusOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberMinusOneActionPerformed
        if (FocusOwnerIndex == 1) {
            int temp = Integer.parseInt(NumberField1.getText()) - 1;
            NumberField1.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 2) {
            int temp = Integer.parseInt(NumberField2.getText()) - 1;
            NumberField2.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 3) {
            int temp = Integer.parseInt(NumberField3.getText()) - 1;
            NumberField3.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 4) {
            int temp = Integer.parseInt(NumberField4.getText()) - 1;
            NumberField4.setText(String.valueOf(temp));
        }
        Validate();
    }//GEN-LAST:event_NumberMinusOneActionPerformed

    private void NumberMinus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberMinus10ActionPerformed
        if (FocusOwnerIndex == 1) {
            int temp = Integer.parseInt(NumberField1.getText()) - 10;
            NumberField1.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 2) {
            int temp = Integer.parseInt(NumberField2.getText()) - 10;
            NumberField2.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 3) {
            int temp = Integer.parseInt(NumberField3.getText()) - 10;
            NumberField3.setText(String.valueOf(temp));
        }
        if (FocusOwnerIndex == 4) {
            int temp = Integer.parseInt(NumberField4.getText()) - 10;
            NumberField4.setText(String.valueOf(temp));
        }
        Validate();
    }//GEN-LAST:event_NumberMinus10ActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        if (FocusOwnerIndex == 1) {
            if (NumberField1.getCaretPosition() <= 0) { // do nothing
            } else {
                NumberField1.setCaretPosition(NumberField1.getCaretPosition() - 1);
                NumberField1.getCaret().setVisible(true);
            }
        } else if (FocusOwnerIndex == 2) {
            if (NumberField2.getCaretPosition() <= 0) { // jump to previous textfield
                FocusOwnerIndex -= 1;
                NumberField1.requestFocus();
                NumberField1.setCaretPosition(NumberField1.getText().length()); // behind last character
            } else {
                NumberField2.setCaretPosition(NumberField2.getCaretPosition() - 1);
                NumberField2.getCaret().setVisible(true);
            }
        } else if (FocusOwnerIndex == 3) {
            if (NumberField3.getCaretPosition() <= 0) { // jump to previous textfield
                FocusOwnerIndex -= 1;
                NumberField2.requestFocus();
                NumberField2.setCaretPosition(NumberField2.getText().length()); // behind last character
            } else {
                NumberField3.setCaretPosition(NumberField3.getCaretPosition() - 1);
                NumberField3.getCaret().setVisible(true);
            }
        } else if (FocusOwnerIndex == 4) {
            if (NumberField4.getCaretPosition() <= 0) { // jump to previous textfield
                FocusOwnerIndex -= 1;
                NumberField3.requestFocus();
                NumberField3.setCaretPosition(NumberField3.getText().length()); // behind last character
            } else {
                NumberField4.setCaretPosition(NumberField4.getCaretPosition() - 1);
                NumberField4.getCaret().setVisible(true);
            }
        }
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        if (FocusOwnerIndex == 1) {
            if (NumberField1.getCaretPosition() >= NumberField1.getText().length()) { // jump to next textfield
                FocusOwnerIndex += 1;
                NumberField2.requestFocus();
                NumberField2.setCaretPosition(0); // before first character
            } else {
                NumberField1.setCaretPosition(NumberField1.getCaretPosition() + 1);
                NumberField1.getCaret().setVisible(true);
            }
        } else if (FocusOwnerIndex == 2) {
            if (NumberField2.getCaretPosition() >= NumberField2.getText().length()) { // jump to next textfield
                FocusOwnerIndex += 1;
                NumberField3.requestFocus();
                NumberField3.setCaretPosition(0); // before first character
            } else {
                NumberField2.setCaretPosition(NumberField2.getCaretPosition() + 1);
                NumberField2.getCaret().setVisible(true);
            }
        } else if (FocusOwnerIndex == 3) {
            if (NumberField3.getCaretPosition() >= NumberField3.getText().length()) { // jump to next textfield
                FocusOwnerIndex += 1;
                NumberField4.requestFocus();
                NumberField4.setCaretPosition(0); // before first character
            } else {
                NumberField3.setCaretPosition(NumberField3.getCaretPosition() + 1);
                NumberField3.getCaret().setVisible(true);
            }
        } else if (FocusOwnerIndex == 4) {
            if (NumberField4.getCaretPosition() >= NumberField4.getText().length()) { // do nothing
            } else {
                NumberField4.setCaretPosition(NumberField4.getCaretPosition() + 1);
                NumberField4.getCaret().setVisible(true);
            }
        }
    }//GEN-LAST:event_RightButtonActionPerformed

    private void NumberField3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NumberField3CaretUpdate
        Validate();
    }//GEN-LAST:event_NumberField3CaretUpdate

    private void NumberField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NumberField2CaretUpdate
        Validate();
    }//GEN-LAST:event_NumberField2CaretUpdate

    private void NumberField4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NumberField4CaretUpdate
        Validate();
    }//GEN-LAST:event_NumberField4CaretUpdate

    private void NumberField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumberField1FocusGained
        FocusOwnerIndex = 1;
        NumberField2.getCaret().setVisible(false);
        NumberField3.getCaret().setVisible(false);
        NumberField4.getCaret().setVisible(false);
    }//GEN-LAST:event_NumberField1FocusGained

    private void NumberField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumberField2FocusGained
        FocusOwnerIndex = 2;
        NumberField1.getCaret().setVisible(false);
        NumberField3.getCaret().setVisible(false);
        NumberField4.getCaret().setVisible(false);
    }//GEN-LAST:event_NumberField2FocusGained

    private void NumberField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumberField3FocusGained
        FocusOwnerIndex = 3;
        NumberField1.getCaret().setVisible(false);
        NumberField2.getCaret().setVisible(false);
        NumberField4.getCaret().setVisible(false);
    }//GEN-LAST:event_NumberField3FocusGained

    private void NumberField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumberField4FocusGained
        FocusOwnerIndex = 4;
        NumberField1.getCaret().setVisible(false);
        NumberField2.getCaret().setVisible(false);
        NumberField3.getCaret().setVisible(false);
    }//GEN-LAST:event_NumberField4FocusGained

    private void NumberClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberClear1ActionPerformed

    private void Number1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Number1MouseClicked
        AppendCharacter("1");
    }//GEN-LAST:event_Number1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EButton BackspaceButton;
    private javax.swing.JPanel ConfirmationPanel;
    private EButton DelButton;
    private javax.swing.JPanel Keypad;
    private EButton LeftButton;
    private EButton Number0;
    private EButton Number1;
    private EButton Number2;
    private EButton Number3;
    private EButton Number4;
    private EButton Number5;
    private EButton Number6;
    private EButton Number7;
    private EButton Number8;
    private EButton Number9;
    private EButton NumberClear;
    private EButton NumberClear1;
    private javax.swing.JTextField NumberField1;
    private javax.swing.JTextField NumberField2;
    private javax.swing.JTextField NumberField3;
    private javax.swing.JTextField NumberField4;
    private EButton NumberMinus10;
    private EButton NumberMinusOne;
    private javax.swing.JPanel NumberPanel;
    private EButton NumberPlusOne;
    private EButton NumberPlusTen;
    private EButton RightButton;
    private EButton SettingsCancelButton;
    private EButton SettingsOKButton;
    private javax.swing.JLabel Validation;
    private javax.swing.JLabel VarName;
    private javax.swing.JLabel VarName1;
    private javax.swing.JLabel VarName2;
    private javax.swing.JLabel VarName3;
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
}
