/*! Copyright (C) 2009 Apertus, All Rights Reserved
 *! Author : Apertus Team
-----------------------------------------------------------------------------**
 *!
 *!  This program is free software: you can redistribute it and/or modify
 *!  it under the terms of the GNU General Public License as published by
 *!  the Free Software Foundation, either version 3 of the License, or
 *!  (at your option) any later version.
 *!
 *!  This program is distributed in the hope that it will be useful,
 *!  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *!  GNU General Public License for more details.
 *!
 *!  You should have received a copy of the GNU General Public License
 *!  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *!
-----------------------------------------------------------------------------**/

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JTextField;
import javax.swing.text.Caret;

public class NumericalInputPanelInteger extends javax.swing.JPanel {

    JTextField FieldParent;
    String TargetCard;
    ElphelVision Parent;

    public NumericalInputPanelInteger(ElphelVision parent) {
        this.Parent = parent;

        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void Load(String Varname, int value, JTextField parent, String targetCard) {
        this.FieldParent = parent;
        this.VarName.setText(Varname);
        this.TargetCard = targetCard;
        this.NumberField.setText(String.valueOf(value));

        NumberField.getCaret().setVisible(true);
    }


    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Keypad = new javax.swing.JPanel();
        Number1 = new EButton(Parent);
        Number2 = new EButton(Parent);
        Number3 = new EButton(Parent);
        Number4 = new EButton(Parent);
        Number5 = new EButton(Parent);
        Number6 = new EButton(Parent);
        Number7 = new EButton(Parent);
        Number8 = new EButton(Parent);
        Number9 = new EButton(Parent);
        NumberClear = new EButton(Parent);
        Number0 = new EButton(Parent);
        NumberPlusOne = new EButton(Parent);
        NumberPlusTen = new EButton(Parent);
        NumberMinusOne = new EButton(Parent);
        NumberMinus10 = new EButton(Parent);
        BackspaceButton = new EButton(Parent);
        DelButton = new EButton(Parent);
        NumberPanel = new javax.swing.JPanel();
        VarName = new javax.swing.JLabel();
        NumberField = new javax.swing.JTextField();
        EndButton = new EButton(Parent);
        RightButton = new EButton(Parent);
        LeftButton = new EButton(Parent);
        Pos1Button = new EButton(Parent);
        Validation = new javax.swing.JLabel();
        ConfirmationPanel = new javax.swing.JPanel();
        SettingsCancelButton = new EButton(Parent);
        SettingsOKButton = new EButton(Parent);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setPreferredSize(new java.awt.Dimension(1024, 600));

        Keypad.setBackground(new java.awt.Color(0, 0, 0));

        Number1.setText("1");
        Number1.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number1.setPreferredSize(new java.awt.Dimension(100, 60));
        Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number1ActionPerformed(evt);
            }
        });

        Number2.setText("2");
        Number2.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number2.setPreferredSize(new java.awt.Dimension(100, 60));
        Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number2ActionPerformed(evt);
            }
        });

        Number3.setText("3");
        Number3.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number3.setPreferredSize(new java.awt.Dimension(100, 60));
        Number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number3ActionPerformed(evt);
            }
        });

        Number4.setText("4");
        Number4.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number4.setPreferredSize(new java.awt.Dimension(100, 60));
        Number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number4ActionPerformed(evt);
            }
        });

        Number5.setText("5");
        Number5.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number5.setPreferredSize(new java.awt.Dimension(100, 60));
        Number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number5ActionPerformed(evt);
            }
        });

        Number6.setText("6");
        Number6.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number6.setPreferredSize(new java.awt.Dimension(100, 60));
        Number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number6ActionPerformed(evt);
            }
        });

        Number7.setText("7");
        Number7.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number7.setPreferredSize(new java.awt.Dimension(100, 60));
        Number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number7ActionPerformed(evt);
            }
        });

        Number8.setText("8");
        Number8.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number8.setPreferredSize(new java.awt.Dimension(100, 60));
        Number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number8ActionPerformed(evt);
            }
        });

        Number9.setText("9");
        Number9.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number9.setPreferredSize(new java.awt.Dimension(100, 60));
        Number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number9ActionPerformed(evt);
            }
        });

        NumberClear.setText("Clear");
        NumberClear.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberClear.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberClearActionPerformed(evt);
            }
        });

        Number0.setText("0");
        Number0.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Number0.setPreferredSize(new java.awt.Dimension(100, 60));
        Number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number0ActionPerformed(evt);
            }
        });

        NumberPlusOne.setText("+1");
        NumberPlusOne.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberPlusOne.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberPlusOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberPlusOneActionPerformed(evt);
            }
        });

        NumberPlusTen.setText("+10");
        NumberPlusTen.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberPlusTen.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberPlusTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberPlusTenActionPerformed(evt);
            }
        });

        NumberMinusOne.setText("-1");
        NumberMinusOne.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberMinusOne.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberMinusOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberMinusOneActionPerformed(evt);
            }
        });

        NumberMinus10.setText("-10");
        NumberMinus10.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        NumberMinus10.setPreferredSize(new java.awt.Dimension(100, 60));
        NumberMinus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberMinus10ActionPerformed(evt);
            }
        });

        BackspaceButton.setText("Backspace");
        BackspaceButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        BackspaceButton.setPreferredSize(new java.awt.Dimension(100, 60));
        BackspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceButtonActionPerformed(evt);
            }
        });

        DelButton.setText("Del");
        DelButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        DelButton.setPreferredSize(new java.awt.Dimension(100, 60));
        DelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeypadLayout = new javax.swing.GroupLayout(Keypad);
        Keypad.setLayout(KeypadLayout);
        KeypadLayout.setHorizontalGroup(
            KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadLayout.createSequentialGroup()
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KeypadLayout.createSequentialGroup()
                            .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(KeypadLayout.createSequentialGroup()
                            .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KeypadLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Number7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumberClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumberMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumberPlusOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberPlusTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(NumberMinusOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        KeypadLayout.setVerticalGroup(
            KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeypadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addComponent(BackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KeypadLayout.createSequentialGroup()
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberPlusTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberPlusOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberMinusOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(KeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NumberPanel.setBackground(java.awt.Color.black);

        VarName.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        VarName.setForeground(new java.awt.Color(255, 255, 255));
        VarName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VarName.setText("Name");
        VarName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VarName.setAlignmentY(0.0F);
        VarName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        VarName.setIconTextGap(0);
        VarName.setInheritsPopupMenu(false);
        VarName.setRequestFocusEnabled(false);
        VarName.setVerifyInputWhenFocusTarget(false);
        VarName.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        NumberField.setBackground(new java.awt.Color(0, 0, 0));
        NumberField.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18));
        NumberField.setForeground(new java.awt.Color(255, 255, 255));
        NumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumberField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 148, 148)));
        NumberField.setCaretColor(new java.awt.Color(255, 255, 255));
        NumberField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                NumberFieldCaretUpdate(evt);
            }
        });

        EndButton.setText("End");
        EndButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        EndButton.setPreferredSize(new java.awt.Dimension(100, 60));
        EndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndButtonActionPerformed(evt);
            }
        });

        RightButton.setText("->");
        RightButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        RightButton.setPreferredSize(new java.awt.Dimension(100, 60));
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });

        LeftButton.setText("<-");
        LeftButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        LeftButton.setPreferredSize(new java.awt.Dimension(100, 60));
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        Pos1Button.setText("Pos1");
        Pos1Button.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
        Pos1Button.setPreferredSize(new java.awt.Dimension(100, 60));
        Pos1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pos1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NumberPanelLayout = new javax.swing.GroupLayout(NumberPanel);
        NumberPanel.setLayout(NumberPanelLayout);
        NumberPanelLayout.setHorizontalGroup(
            NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VarName)
                    .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(NumberPanelLayout.createSequentialGroup()
                            .addComponent(Pos1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(EndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        NumberPanelLayout.setVerticalGroup(
            NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VarName)
                .addGap(18, 18, 18)
                .addComponent(NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pos1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Validation.setForeground(new java.awt.Color(180, 1, 1));

        ConfirmationPanel.setBackground(java.awt.Color.black);

        SettingsCancelButton.setText("Cancel");
        SettingsCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsCancelButtonActionPerformed(evt);
            }
        });

        SettingsOKButton.setText("OK");
        SettingsOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfirmationPanelLayout = new javax.swing.GroupLayout(ConfirmationPanel);
        ConfirmationPanel.setLayout(ConfirmationPanelLayout);
        ConfirmationPanelLayout.setHorizontalGroup(
            ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationPanelLayout.createSequentialGroup()
                .addComponent(SettingsOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SettingsCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ConfirmationPanelLayout.setVerticalGroup(
            ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SettingsOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(SettingsCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Validation, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(922, Short.MAX_VALUE)
                .addComponent(ConfirmationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Keypad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Validation, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Keypad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(ConfirmationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsOKButtonActionPerformed
        this.FieldParent.setText(NumberField.getText());

        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), TargetCard);
    }//GEN-LAST:event_SettingsOKButtonActionPerformed

    private void SettingsCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsCancelButtonActionPerformed
        CardLayout cl = (CardLayout) (Parent.GetCardManager().getLayout());
        cl.show(Parent.GetCardManager(), TargetCard);
    }//GEN-LAST:event_SettingsCancelButtonActionPerformed

    private void NumberFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_NumberFieldCaretUpdate
    }//GEN-LAST:event_NumberFieldCaretUpdate

    void AppendCharacter(String character) {
        int tmpcaretpos = NumberField.getCaretPosition(); // save positon of the caret so we can use it again after replacing the string
        NumberField.setText(NumberField.getText().substring(0, NumberField.getCaretPosition()) + character + NumberField.getText().substring(NumberField.getCaretPosition(), NumberField.getText().length()));
        NumberField.setCaretPosition(tmpcaretpos + 1); // use the save caret position again
        NumberField.getCaret().setVisible(true);
    }

    private void Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number1ActionPerformed
        AppendCharacter("1");
    }//GEN-LAST:event_Number1ActionPerformed

    private void Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number2ActionPerformed
        AppendCharacter("2");
    }//GEN-LAST:event_Number2ActionPerformed

    private void Number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number3ActionPerformed
        AppendCharacter("3");
    }//GEN-LAST:event_Number3ActionPerformed

    private void Number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number4ActionPerformed
        AppendCharacter("4");
    }//GEN-LAST:event_Number4ActionPerformed

    private void Number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number5ActionPerformed
        AppendCharacter("5");
    }//GEN-LAST:event_Number5ActionPerformed

    private void Number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number6ActionPerformed
        AppendCharacter("6");
    }//GEN-LAST:event_Number6ActionPerformed

    private void Number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number7ActionPerformed
        AppendCharacter("7");
    }//GEN-LAST:event_Number7ActionPerformed

    private void Number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number8ActionPerformed
        AppendCharacter("8");
    }//GEN-LAST:event_Number8ActionPerformed

    private void Number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number9ActionPerformed
        AppendCharacter("9");
    }//GEN-LAST:event_Number9ActionPerformed

    private void NumberClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberClearActionPerformed
        NumberField.setText("");
    }//GEN-LAST:event_NumberClearActionPerformed

    private void Number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number0ActionPerformed
        AppendCharacter("0");
    }//GEN-LAST:event_Number0ActionPerformed

    private void DelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelButtonActionPerformed
        if (NumberField.getCaretPosition() != NumberField.getText().length()) { // only do something if the caret is not the at the end
            int tmpcaretpos = NumberField.getCaretPosition();
            NumberField.setText(NumberField.getText().substring(0, NumberField.getCaretPosition()) + NumberField.getText().substring(NumberField.getCaretPosition() + 1, NumberField.getText().length()));
            NumberField.setCaretPosition(tmpcaretpos);
        }
    }//GEN-LAST:event_DelButtonActionPerformed

    private void BackspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceButtonActionPerformed
        if (NumberField.getCaretPosition() != 0) { // only do something if the caret is not the at the beginning
            int tmpcaretpos = NumberField.getCaretPosition();
            NumberField.setText(NumberField.getText().substring(0, NumberField.getCaretPosition() - 1) + NumberField.getText().substring(NumberField.getCaretPosition(), NumberField.getText().length()));
            NumberField.setCaretPosition(tmpcaretpos - 1);
        }
    }//GEN-LAST:event_BackspaceButtonActionPerformed

    private void NumberPlusOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberPlusOneActionPerformed
        int temp = Integer.parseInt(NumberField.getText()) + 1;
        if (temp < 0) {
            temp = 0;
        }
        NumberField.setText(String.valueOf(temp));
    }//GEN-LAST:event_NumberPlusOneActionPerformed

    private void Pos1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pos1ButtonActionPerformed
        NumberField.setCaretPosition(0);
        NumberField.getCaret().setVisible(true);
    }//GEN-LAST:event_Pos1ButtonActionPerformed

    private void EndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndButtonActionPerformed
        NumberField.setCaretPosition(NumberField.getText().length());
        NumberField.getCaret().setVisible(true);
    }//GEN-LAST:event_EndButtonActionPerformed

    private void NumberPlusTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberPlusTenActionPerformed
        int temp = Integer.parseInt(NumberField.getText()) + 10;
        if (temp < 0) {
            temp = 0;
        }
        NumberField.setText(String.valueOf(temp));        // TODO add your handling code here:
    }//GEN-LAST:event_NumberPlusTenActionPerformed

    private void NumberMinusOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberMinusOneActionPerformed
        int temp = Integer.parseInt(NumberField.getText()) - 1;
        if (temp < 0) {
            temp = 0;
        }
        NumberField.setText(String.valueOf(temp));
    }//GEN-LAST:event_NumberMinusOneActionPerformed

    private void NumberMinus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberMinus10ActionPerformed
        int temp = Integer.parseInt(NumberField.getText()) - 10;
        if (temp < 0) {
            temp = 0;
        }
        NumberField.setText(String.valueOf(temp));
    }//GEN-LAST:event_NumberMinus10ActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        NumberField.setCaretPosition(NumberField.getCaretPosition() - 1);
        NumberField.getCaret().setVisible(true);
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        NumberField.setCaretPosition(NumberField.getCaretPosition() + 1);
        NumberField.getCaret().setVisible(true);
    }//GEN-LAST:event_RightButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EButton BackspaceButton;
    private javax.swing.JPanel ConfirmationPanel;
    private EButton DelButton;
    private EButton EndButton;
    private javax.swing.JPanel Keypad;
    private EButton LeftButton;
    private EButton Number0;
    private EButton Number1;
    private EButton Number2;
    private EButton Number3;
    private EButton Number4;
    private EButton Number5;
    private EButton Number6;
    private EButton Number7;
    private EButton Number8;
    private EButton Number9;
    private EButton NumberClear;
    private javax.swing.JTextField NumberField;
    private EButton NumberMinus10;
    private EButton NumberMinusOne;
    private javax.swing.JPanel NumberPanel;
    private EButton NumberPlusOne;
    private EButton NumberPlusTen;
    private EButton Pos1Button;
    private EButton RightButton;
    private EButton SettingsCancelButton;
    private EButton SettingsOKButton;
    private javax.swing.JLabel Validation;
    private javax.swing.JLabel VarName;
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
}
